/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TablaLibros.java
 *
 * Created on 18-ene-2011, 11:19:03
 */
package gui;


import logica.GestionLibreria;
import modelo.Libro;

import java.util.List;

import modelo.LibreriaException;

/**
 *
 * ¡para que funcione correctamente quitar columna precio en la tabla!
 */
public class IUGraficaLibreria extends javax.swing.JFrame {

	private static final long serialVersionUID = -3219485802187078260L;

	/** Creates new form TablaLibros */
	public IUGraficaLibreria() {
		initOtherComponents();
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Catalogo de Libros");

		jTable1.setModel(new ModeloTablaLibros(datos, cabeceras));
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 315,
								Short.MAX_VALUE).addGap(61, 61, 61)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 100,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(155, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new IUGraficaLibreria().setVisible(true);
			}
		});
	}

	private void initOtherComponents() {
        try {
        	String isbn=javax.swing.JOptionPane.showInputDialog("Instroduce isbn");
        	String copias=javax.swing.JOptionPane.showInputDialog("Instroduce número de copias");
            //Inicialización de la tabla con el catálogo de libros
            List<Libro> libros = new GestionLibreria().actualizaLibreria(new Integer(isbn), new Integer(copias));
        	//List<Libro> libros = new GestionLibreria().actualizaLibreria(12453, 12);
            int nLibros = libros.size();
            //Obtengo el número de campos de un objeto Libro
            int nCampos = Libro.class.getDeclaredFields().length;
            datos = new Object[nLibros][nCampos];
            cabeceras = new Object[nCampos];
            for (int i = 0; i < nLibros; i++) {
                Object[] libro = libros.get(i).toArray();
                for (int j = 0; j < nCampos; j++) {
                    datos[i][j] = libro[j];
                    cabeceras[j]="Campo "+j;
                }
            }

        } catch (LibreriaException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error y la aplicación se cerrará");
            System.exit(-1);
        }

    }

	private Object[][] datos;
	private Object[] cabeceras;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables
}
