drop database if exists segurosTema4P3E3;

create database segurosTema4P3E3;

use segurosTema4P3E3; 

CREATE TABLE NIF(
	ID_NIF integer NOT NULL AUTO_INCREMENT,
	NIF varchar(15) NOT NULL UNIQUE,
	PRIMARY KEY(ID_NIF)
);

CREATE TABLE ENFERMEDADES(
	ID_ENFERMEDAD integer NOT NULL AUTO_INCREMENT,
	CORAZON CHAR(1) NOT NULL,
	ESTOMACAL CHAR(1) NOT NULL,
	RINYONES CHAR(1) NOT NULL,
	ALERGIA CHAR(1) NOT NULL,
	NOMBRE_ALERGIA TEXT,
	PRIMARY KEY(ID_ENFERMEDAD)
);

CREATE TABLE COBERTURAS(
	ID_COBERTURA integer NOT NULL AUTO_INCREMENT,
	OFTALMOLOGIA CHAR(1) NOT NULL,
	DENTAL CHAR(1) NOT NULL,
	FECUNDACION_IN_VITRO CHAR(1) NOT NULL,
	PRIMARY KEY(ID_COBERTURA)
);

CREATE TABLE SEGURO(
	ID_SEGURO integer NOT NULL AUTO_INCREMENT,
	NIF_ID integer NOT NULL,
	NOMBRE varchar(20) NOT NULL,
	APE1 varchar(20) NOT NULL,
	APE2 varchar(20) NOT NULL,
	EDAD integer NOT NULL,
	SEXO integer NOT NULL,
	CASADO BOOLEAN NOT NULL,
	HIJOS integer NOT NULL,
	EMBARAZADA BOOLEAN NOT NULL,
	COBERTURA_ID integer NOT NULL,
	ENFERMEDADES_ID integer NOT NULL,
	FECHA_CREACION datetime NOT NULL,
	PRIMARY KEY(ID_SEGURO)
);

CREATE TABLE Asistencia_Medica(
	ID_ASISTENCIA integer NOT NULL AUTO_INCREMENT,
	DESCRIPCION text,
	LUGAR varchar(30) NOT NULL,
	EXPLICACION longtext NOT NULL,
	TIPO_ASISTENCIA varchar(15) NOT NULL CHECK(TIPO_ASISTENCIA='Hospitalaria' OR TIPO_ASISTENCIA='Ambulatoria' OR TIPO_ASISTENCIA='CentroSalud' OR TIPO_ASISTENCIA='Domiciliaria'),
	FECHA DATE NOT NULL,
	HORA TIME NOT NULL,
	IMPORTE DECIMAL(10,2) NOT NULL,
	SEGURO integer NOT NULL,
	PRIMARY KEY(ID_ASISTENCIA)
);

ALTER TABLE seguro
ADD CONSTRAINT nifid
FOREIGN KEY (NIF_ID)
REFERENCES nif(ID_NIF);

ALTER TABLE seguro
ADD CONSTRAINT enfid
FOREIGN KEY (ENFERMEDADES_ID)
REFERENCES enfermedades(ID_ENFERMEDAD);

ALTER TABLE seguro
ADD CONSTRAINT cobid
FOREIGN KEY (COBERTURA_ID)
REFERENCES coberturas(ID_COBERTURA);

ALTER TABLE Asistencia_Medica
ADD CONSTRAINT segur
FOREIGN KEY (SEGURO)
REFERENCES seguro(ID_SEGURO);


insert into NIF(NIF) values('49963216R');
insert into NIF(NIF) values('46569898Z');
insert into NIF(NIF) values('78949598K');
insert into NIF(NIF) values('21684981Y');
insert into NIF(NIF) values('28884642T');

insert into COBERTURAS(OFTALMOLOGIA,DENTAL,FECUNDACION_IN_VITRO) values('F','T','F');
insert into COBERTURAS(OFTALMOLOGIA,DENTAL,FECUNDACION_IN_VITRO) values('T','T','F');
insert into COBERTURAS(OFTALMOLOGIA,DENTAL,FECUNDACION_IN_VITRO) values('T','F','F');
insert into COBERTURAS(OFTALMOLOGIA,DENTAL,FECUNDACION_IN_VITRO) values('T','T','F');
insert into COBERTURAS(OFTALMOLOGIA,DENTAL,FECUNDACION_IN_VITRO) values('F','F','T');

insert into ENFERMEDADES(CORAZON,ESTOMACAL,RINYONES,ALERGIA,NOMBRE_ALERGIA) values('Y','Y','Y','N','');
insert into ENFERMEDADES(CORAZON,ESTOMACAL,RINYONES,ALERGIA,NOMBRE_ALERGIA) values('Y','N','N','Y','Pescado blanco y nueces');
insert into ENFERMEDADES(CORAZON,ESTOMACAL,RINYONES,ALERGIA,NOMBRE_ALERGIA) values('Y','N','Y','N','');
insert into ENFERMEDADES(CORAZON,ESTOMACAL,RINYONES,ALERGIA,NOMBRE_ALERGIA) values('N','N','N','N','');
insert into ENFERMEDADES(CORAZON,ESTOMACAL,RINYONES,ALERGIA,NOMBRE_ALERGIA) values('N','N','N','N','Lacteos, Frutos secos y Metales blandos');

insert into SEGURO(NIF_ID,NOMBRE,APE1,APE2,EDAD,SEXO,CASADO,HIJOS,EMBARAZADA,COBERTURA_ID,ENFERMEDADES_ID,FECHA_CREACION) values(1,'Carlos','Sainz','Barrameda',35,0,true,2,false,2,1,'2014-01-18 16:33:41');
insert into SEGURO(NIF_ID,NOMBRE,APE1,APE2,EDAD,SEXO,CASADO,HIJOS,EMBARAZADA,COBERTURA_ID,ENFERMEDADES_ID,FECHA_CREACION) values(4,'Pepa','Grandas','Dominguez',34,1,false,0,false,5,2,'2012-04-09 08:40:00');
insert into SEGURO(NIF_ID,NOMBRE,APE1,APE2,EDAD,SEXO,CASADO,HIJOS,EMBARAZADA,COBERTURA_ID,ENFERMEDADES_ID,FECHA_CREACION) values(3,'Maria','Garcia','Lozano',28,1,true,1,true,1,4,'2004-08-21 10:15:06');
insert into SEGURO(NIF_ID,NOMBRE,APE1,APE2,EDAD,SEXO,CASADO,HIJOS,EMBARAZADA,COBERTURA_ID,ENFERMEDADES_ID,FECHA_CREACION) values(2,'Francisco','Romo','Auditore',70,0,false,0,false,3,3,'2006-03-30 13:44:04');
insert into SEGURO(NIF_ID,NOMBRE,APE1,APE2,EDAD,SEXO,CASADO,HIJOS,EMBARAZADA,COBERTURA_ID,ENFERMEDADES_ID,FECHA_CREACION) values(5,'Marcos','Pirri','Martin',52,0,false,1,false,4,5,'2012-12-12 15:22:12');

insert into ASISTENCIA_MEDICA(DESCRIPCION,LUGAR,EXPLICACION,TIPO_ASISTENCIA,FECHA,HORA,IMPORTE,SEGURO) values('Descripcion1','Madrid','Ataque epileptico','Hospitalaria','2015-09-28','11:45:30',9452.25,1);
insert into ASISTENCIA_MEDICA(DESCRIPCION,LUGAR,EXPLICACION,TIPO_ASISTENCIA,FECHA,HORA,IMPORTE,SEGURO) values('Descripcion2','Barcelona','Gripe','CentroSalud','2015-01-02','16:10:20',400.23,2);
insert into ASISTENCIA_MEDICA(DESCRIPCION,LUGAR,EXPLICACION,TIPO_ASISTENCIA,FECHA,HORA,IMPORTE,SEGURO) values('Descripcion3','Valladolid','Ebola','Hospitalaria','2015-11-02','20:00:10',30400.51,3);
insert into ASISTENCIA_MEDICA(DESCRIPCION,LUGAR,EXPLICACION,TIPO_ASISTENCIA,FECHA,HORA,IMPORTE,SEGURO) values('Descripcion4','Murcia','Ataque al corazon','Domiciliaria','2015-08-12','12:45:00',4860.75,4);
insert into ASISTENCIA_MEDICA(DESCRIPCION,LUGAR,EXPLICACION,TIPO_ASISTENCIA,FECHA,HORA,IMPORTE,SEGURO) values('Descripcion5','Valencia','Choque etilico','Ambulatoria','2014-04-18','02:45:30',512.25,5);
insert into ASISTENCIA_MEDICA(DESCRIPCION,LUGAR,EXPLICACION,TIPO_ASISTENCIA,FECHA,HORA,IMPORTE,SEGURO) values('Descripcion6','Valencia','Choque etilico','Ambulatoria','2014-05-02','03:16:45',580.90,5);